services:
  slurmapi:
    image: edison-slurm-api:19
    hostname: slurmapi
    user: admin
    volumes:
      - shared-vol:/home/admin
      - shared-program:/PROGRAMS
    ports:
      - "8000:8000"
      - "3000:3000"
    expose:
      - "8000"
      - "3000"
  slurmmaster:
    image: edison-slurm-master:19
    hostname: slurmmaster
    user: admin
    volumes:
      - shared-vol:/home/admin
      - shared-program:/PROGRAMS
    ports:
      - "6817:6817"
      - "6818:6818"
      - "6819:6819"
  slurmnode1:
    image: edison-slurm-node:19
    hostname: slurmnode1
    user: admin
    volumes:
      - shared-vol:/home/admin
      - shared-program:/PROGRAMS
    links:
      - slurmmaster
volumes:
  shared-vol:
  shared-program:
